apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dotnetapp
    tier: web
  name: dotnetapp
spec:
  containers:
  - image: fjb4/dotnetapp
    name: dotnetapp
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
