apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-svc
  labels:
    app: dotnetapp-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: dotnetapp
