apiVersion: v1
kind: Pod
metadata:
  name: dotnetapp-pod
  labels:
    app: dotnetapp
    tier: frontend
spec:
  containers:
  - image: fjb4/dotnetapp
    name: dotnetapp-container
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
