apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
      name: dotnetapp
    spec:
      containers:
      - image: fjb4/dotnetapp
        name: dotnetapp
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
