apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-dep
  labels:
    app: dotnetapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - image: registry.gke.jb-cloud.com/library/dotnetapp
          name: dotnetapp-container
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
