apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-dep
  labels:
    app: dotnetapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - image: nginx
        name: dotnetapp-container
        imagePullPolicy: Always
        ports:
          - containerPort: 80
